---
- name: Install required packages for Docker.
  apt:
    name: "{{ PREREQUISITE_DOCKER_PACKAGES }}"
    update_cache: yes

- name: Add Docker official GPG key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker repository (stable).
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
  when: ansible_distribution == 'Debian'


- name: Install docker-ce.
  apt:
    name: docker-ce={{ DOCKER_VERSION_DEBIAN }}
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Install docker repository (stable).
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
  when: ansible_distribution == 'Ubuntu'

- name: Install docker-ce.
  apt:
    name: docker-ce={{ DOCKER_VERSION_UBUNTU }}
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install docker Python library
  pip:
    name: docker
